language: node_js
sudo: false
node_js:
  - '0.12'
  - '0.10'
  - iojs

matrix:
  allow_failures:
    - node_js: iojs

branches:
  only:
    - master
    - release

before_script:
  - npm install gulp -g
  - npm install bower -g

script:
  - npm install
  - bower install
  - gulp

cache:
  directories:
    - node_modules
    - bower_components

notifications:
  email:
    - loljoho@gmail.com
